---
title: Curfew Studio
timezone: America/New_York
collections:
  docs:
    title: Docs
    output: true
  loosies:
    title: Loosies
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  work:
    title: Work
    output: true
defaults:
- scope:
    path: ''
    type: loosies
  values:
    layout: project
- scope:
    path: ''
    type: work
  values:
    layout: project
- scope:
    path: ''
    type: docs
  values:
    layout: about
name: Curfew Studio
description: The design studio of Drew Albinson.
author:
  name: Curfew Studio
  email: yo@curfewstudio.com
include:
- ".htaccess"
future: true
show_drafts: true
markdown: kramdown
highlighter: rouge
permalink: pretty
sass:
  sass-dir: _sass
  style: compressed
url: https://curfewstudio.github.io/
